// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    return $('body').on('click', '.purpose', function() {
      $('.purpose').removeClass('selected-purpose');
      $('.purpose').attr('class', function(i, c) {
        return c.replace(/_hover/g, '');
      });
      $(this).addClass('selected-purpose');
      $(this).attr('class', function(i, c) {
        return c.replace(/_icon/, '_icon_hover');
      });
      console.log($(this).attr('id'));
      return $('#purpose').val($(this).attr('id'));
    });
  });

  $(document).ready(function() {
    var loadContent;
    $('#main_content').load('company.html').fadeIn('fast');
    loadContent = function(address) {
      return $('#main_content').fadeOut('fast', function() {
        return $(this).load(address).fadeIn('fast');
      });
    };
    $('#logo').click(function() {
      return loadContent('home.html');
    });
    $('body').on('click', 'a:not(.direct)', function(event) {
      var href;
      event.preventDefault();
      href = $(this).attr("href");
      return loadContent(href);
    });
    return $('body').on('click', '.project', function() {
      return loadContent('work-' + $(this).attr('id') + '.html');
    });
  });

  $(document).ready(function() {
    $('body').on('mouseenter ', '.project', function() {
      return $(this).stop().animate({
        backgroundColor: "#eeeeee"
      });
    });
    return $('body').on('mouseleave ', '.project', function() {
      return $(this).stop().animate({
        backgroundColor: '#ffffff'
      });
    });
  });

}).call(this);
