// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var loadContent;
    $.ajax('home.html', {
      type: 'GET',
      cache: false,
      success: function(data) {
        return $('#main_content').html(data).fadeIn('fast');
      }
    });
    loadContent = function(data) {
      return $('#main_content').fadeOut('fast', function() {
        return $(this).html(data).fadeIn('fast');
      });
    };
    $('#logo').click(function() {
      return $.ajax('home.html', {
        type: 'GET',
        success: function(data) {
          return loadContent(data);
        }
      });
    });
    return $('body').on('click', 'a:not(.direct)', function(event) {
      var href;
      event.preventDefault();
      href = $(this).attr("href");
      return $.ajax(href, {
        type: 'GET',
        success: function(data) {
          return loadContent(data);
        }
      });
    });
  });

}).call(this);
